name: Comunicador de la Legión

on:
  workflow_dispatch:
    input:
      villano:
        description: "¿Que villano envia el mensaje?"
        required: true
        type: choice
        options:
          - Lex tuthor
          - joker 
          - mistyique
          - Brainiac
          - magneto

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4